{
  "formatVersion": "1.1",
  "component": {
    "group": "io.temporal",
    "module": "temporal-bom",
    "version": "0.20.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "io.temporal",
          "module": "temporal-kotlin",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-opentracing",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-remote-data-encoder",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-sdk",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-serviceclient",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-shaded",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-spring-boot-autoconfigure",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-spring-boot-starter",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-test-server",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-testing",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-envconfig",
          "version": {
            "requires": "0.20.2"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "io.temporal",
          "module": "temporal-kotlin",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-opentracing",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-remote-data-encoder",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-sdk",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-serviceclient",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-shaded",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-spring-boot-autoconfigure",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-spring-boot-starter",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-test-server",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-testing",
          "version": {
            "requires": "0.20.2"
          }
        },
        {
          "group": "io.temporal",
          "module": "temporal-envconfig",
          "version": {
            "requires": "0.20.2"
          }
        }
      ]
    }
  ]
}
